swagger: '2.0'
info:
  title: MY API
  x-ibm-name: my-api
  version: 1.0.0
x-ibm-configuration:
  cors:
    enabled: false
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  assembly:
    execute:
      - gatewayscript:
          version: 2.0.0
          title: gatewayscript
          source: session.output.write('{"Msg":"OK"}')
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  activity-log:
    enabled: true
    success-content: activity
    error-content: payload
basePath: /test-api
paths:
  /:
    get:
      responses:
        '200':
          description: success
          schema:
            type: string
      consumes: []
      produces: []
    put:
      responses:
        '200':
          description: success
          schema:
            type: string
      consumes: []
      produces: []
    post:
      responses:
        '200':
          description: success
          schema:
            type: string
      consumes: []
      produces: []
    delete:
      responses:
        '200':
          description: success
          schema:
            type: string
      consumes: []
      produces: []
    head:
      responses:
        '200':
          description: success
          schema:
            type: string
      consumes: []
      produces: []
    patch:
      responses:
        '200':
          description: success
          schema:
            type: string
      consumes: []
      produces: []
    options:
      responses:
        '200':
          description: success
          schema:
            type: string
      consumes: []
      produces: []
schemes:
  - https
securityDefinitions:
  oa:
    type: oauth2
    x-ibm-oauth-provider: test-auth
    flow: accessCode
    authorizationUrl: https://$(catalog.url)/test-auth/oauth2/authorize
    tokenUrl: https://$(catalog.url)/test-auth/oauth2/token
    scopes:
      apic: Sample scope description 1
  API Key:
    type: apiKey
    x-key-type: client_id
    name: ci
    in: query
security:
  - oa:
      - apic
  - API Key: []
